import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';

const options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'Portfolio API',
            version: '1.0.0',
            description: 'Portfolio API with autogenerated swagger doc',
        },
        servers: [
            {
                url: 'http://localhost:3000/api',
                description: 'Development server',
            },
        ],
    },
    apis: ['@/app/api/v1/**/*.ts'],
};

const specs = swaggerJsdoc(options);

export const swaggerMiddleware = swaggerUi.serve;
export const swaggerUiSetup = swaggerUi.setup(specs);